apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres password"
  JWT_PRIVATE_KEY: "ed25519 private key"
  JWT_PUBLIC_KEY: "ed25519 public key"